/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as VerifyIdRouteImport } from './routes/verify/$id'
import { Route as AuthenticatedValidationsRouteImport } from './routes/_authenticated/validations'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedPollsRouteImport } from './routes/_authenticated/polls'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedLawsRouteImport } from './routes/_authenticated/laws'
import { Route as AuthenticatedHousesRouteImport } from './routes/_authenticated/houses'
import { Route as AuthenticatedFamiliesRouteImport } from './routes/_authenticated/families'
import { Route as AuthenticatedCitizensRouteImport } from './routes/_authenticated/citizens'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests/index'
import { Route as AuthenticatedRequestsSignatoriesRouteImport } from './routes/_authenticated/requests/signatories'
import { Route as AuthenticatedRequestsAdminRouteImport } from './routes/_authenticated/requests/admin'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidationsRoute =
  AuthenticatedValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPollsRoute = AuthenticatedPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLawsRoute = AuthenticatedLawsRouteImport.update({
  id: '/laws',
  path: '/laws',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHousesRoute = AuthenticatedHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliesRoute = AuthenticatedFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCitizensRoute = AuthenticatedCitizensRouteImport.update({
  id: '/citizens',
  path: '/citizens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedRequestsSignatoriesRoute =
  AuthenticatedRequestsSignatoriesRouteImport.update({
    id: '/signatories',
    path: '/signatories',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedRequestsAdminRoute =
  AuthenticatedRequestsAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/citizens': typeof AuthenticatedCitizensRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/houses': typeof AuthenticatedHousesRoute
  '/laws': typeof AuthenticatedLawsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/validations': typeof AuthenticatedValidationsRoute
  '/verify/$id': typeof VerifyIdRoute
  '/auth/': typeof AuthIndexRoute
  '/requests/admin': typeof AuthenticatedRequestsAdminRoute
  '/requests/signatories': typeof AuthenticatedRequestsSignatoriesRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/citizens': typeof AuthenticatedCitizensRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/houses': typeof AuthenticatedHousesRoute
  '/laws': typeof AuthenticatedLawsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/validations': typeof AuthenticatedValidationsRoute
  '/verify/$id': typeof VerifyIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/requests/admin': typeof AuthenticatedRequestsAdminRoute
  '/requests/signatories': typeof AuthenticatedRequestsSignatoriesRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/citizens': typeof AuthenticatedCitizensRoute
  '/_authenticated/families': typeof AuthenticatedFamiliesRoute
  '/_authenticated/houses': typeof AuthenticatedHousesRoute
  '/_authenticated/laws': typeof AuthenticatedLawsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/polls': typeof AuthenticatedPollsRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/validations': typeof AuthenticatedValidationsRoute
  '/verify/$id': typeof VerifyIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/requests/admin': typeof AuthenticatedRequestsAdminRoute
  '/_authenticated/requests/signatories': typeof AuthenticatedRequestsSignatoriesRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/citizens'
    | '/families'
    | '/houses'
    | '/laws'
    | '/meetings'
    | '/polls'
    | '/requests'
    | '/users'
    | '/validations'
    | '/verify/$id'
    | '/auth/'
    | '/requests/admin'
    | '/requests/signatories'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-assistant'
    | '/citizens'
    | '/families'
    | '/houses'
    | '/laws'
    | '/meetings'
    | '/polls'
    | '/users'
    | '/validations'
    | '/verify/$id'
    | '/'
    | '/auth'
    | '/requests/admin'
    | '/requests/signatories'
    | '/requests'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/citizens'
    | '/_authenticated/families'
    | '/_authenticated/houses'
    | '/_authenticated/laws'
    | '/_authenticated/meetings'
    | '/_authenticated/polls'
    | '/_authenticated/requests'
    | '/_authenticated/users'
    | '/_authenticated/validations'
    | '/verify/$id'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/requests/admin'
    | '/_authenticated/requests/signatories'
    | '/_authenticated/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  VerifyIdRoute: typeof VerifyIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validations': {
      id: '/_authenticated/validations'
      path: '/validations'
      fullPath: '/validations'
      preLoaderRoute: typeof AuthenticatedValidationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/polls': {
      id: '/_authenticated/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthenticatedPollsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laws': {
      id: '/_authenticated/laws'
      path: '/laws'
      fullPath: '/laws'
      preLoaderRoute: typeof AuthenticatedLawsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses': {
      id: '/_authenticated/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof AuthenticatedHousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/families': {
      id: '/_authenticated/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof AuthenticatedFamiliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizens': {
      id: '/_authenticated/citizens'
      path: '/citizens'
      fullPath: '/citizens'
      preLoaderRoute: typeof AuthenticatedCitizensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/requests/signatories': {
      id: '/_authenticated/requests/signatories'
      path: '/signatories'
      fullPath: '/requests/signatories'
      preLoaderRoute: typeof AuthenticatedRequestsSignatoriesRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/requests/admin': {
      id: '/_authenticated/requests/admin'
      path: '/admin'
      fullPath: '/requests/admin'
      preLoaderRoute: typeof AuthenticatedRequestsAdminRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
  }
}

interface AuthenticatedRequestsRouteChildren {
  AuthenticatedRequestsAdminRoute: typeof AuthenticatedRequestsAdminRoute
  AuthenticatedRequestsSignatoriesRoute: typeof AuthenticatedRequestsSignatoriesRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

const AuthenticatedRequestsRouteChildren: AuthenticatedRequestsRouteChildren = {
  AuthenticatedRequestsAdminRoute: AuthenticatedRequestsAdminRoute,
  AuthenticatedRequestsSignatoriesRoute: AuthenticatedRequestsSignatoriesRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
}

const AuthenticatedRequestsRouteWithChildren =
  AuthenticatedRequestsRoute._addFileChildren(
    AuthenticatedRequestsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedCitizensRoute: typeof AuthenticatedCitizensRoute
  AuthenticatedFamiliesRoute: typeof AuthenticatedFamiliesRoute
  AuthenticatedHousesRoute: typeof AuthenticatedHousesRoute
  AuthenticatedLawsRoute: typeof AuthenticatedLawsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedPollsRoute: typeof AuthenticatedPollsRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedValidationsRoute: typeof AuthenticatedValidationsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedCitizensRoute: AuthenticatedCitizensRoute,
  AuthenticatedFamiliesRoute: AuthenticatedFamiliesRoute,
  AuthenticatedHousesRoute: AuthenticatedHousesRoute,
  AuthenticatedLawsRoute: AuthenticatedLawsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedPollsRoute: AuthenticatedPollsRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedValidationsRoute: AuthenticatedValidationsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  VerifyIdRoute: VerifyIdRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
